[build]
  publish = "."

# Cache images and PDFs for 1 year (Standard practice for static assets)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security Headers (Good for your CS knowledge/security interest)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
